import React, { useRef } from "react";
import { motion } from "framer-motion";
import {
  Printer,
  Download,
  BookOpen,
  GraduationCap,
  Award,
  Building,
  CheckCircle2,
  ShieldCheck,
  FileText,
} from "lucide-react";
import { TranscriptData } from "../../../types";

interface TranscriptViewerProps {
  transcript: TranscriptData;
}

export const TranscriptViewer: React.FC<TranscriptViewerProps> = ({ transcript }) => {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = () => {
    alert("Official Transcript PDF Export requested. Preparing digital signature verification watermarks and downloading...");
  };

  return (
    <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-sm mb-6">
      {/* HEADER CONTROLS */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100 dark:border-slate-800">
        <div>
          <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-600 dark:text-indigo-400" /> Official Academic Transcript
          </h2>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
            Verified, seal-compatible official academic transcript layout generated by StudyMate Engine.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 text-slate-700 dark:text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors"
          >
            <Printer className="w-4 h-4 text-slate-500" /> Print Transcript
          </button>
          <button
            onClick={handleExportPDF}
            className="px-4 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-sm"
          >
            <Download className="w-4 h-4" /> Export Signed PDF
          </button>
        </div>
      </div>

      {/* PRINTABLE TRANSCRIPT SHEET */}
      <div
        ref={printRef}
        className="mt-6 p-8 bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-100 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-inner font-serif"
      >
        {/* INSTITUTIONAL HEADER */}
        <div className="text-center pb-6 border-b-2 border-slate-900 dark:border-slate-100 mb-6">
          <div className="inline-flex items-center justify-center p-3 rounded-full bg-indigo-50 dark:bg-indigo-950/60 text-indigo-900 dark:text-indigo-200 mb-2 border border-indigo-200 dark:border-indigo-800">
            <Building className="w-8 h-8" />
          </div>
          <h1 className="text-xl font-extrabold uppercase tracking-widest text-slate-900 dark:text-white">
            {transcript.institutionName}
          </h1>
          <p className="text-xs font-sans font-semibold text-slate-600 dark:text-slate-400 mt-1 uppercase tracking-wider">
            {transcript.faculty} • {transcript.department}
          </p>
          <p className="text-xs font-sans text-slate-500 dark:text-slate-400 mt-0.5">
            OFFICIAL ACADEMIC TRANSCRIPT OF ACADEMIC RECORD
          </p>
        </div>

        {/* STUDENT METADATA GRID */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 font-sans text-xs mb-6">
          <div>
            <span className="text-slate-400 block text-[11px] font-semibold uppercase">Student Name:</span>
            <span className="font-bold text-slate-900 dark:text-white">{transcript.studentName}</span>
          </div>
          <div>
            <span className="text-slate-400 block text-[11px] font-semibold uppercase">Matriculation No:</span>
            <span className="font-bold text-slate-900 dark:text-white font-mono">{transcript.matricNumber}</span>
          </div>
          <div>
            <span className="text-slate-400 block text-[11px] font-semibold uppercase">Programme:</span>
            <span className="font-bold text-slate-900 dark:text-white">{transcript.programme}</span>
          </div>
          <div>
            <span className="text-slate-400 block text-[11px] font-semibold uppercase">Issue Date:</span>
            <span className="font-bold text-slate-900 dark:text-white">{transcript.issueDate}</span>
          </div>
        </div>

        {/* SEMESTERS BREAKDOWN */}
        <div className="space-y-6 font-sans">
          {transcript.semesters.map((sem, sIdx) => (
            <div key={sem.id} className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
              <div className="bg-slate-100 dark:bg-slate-800/80 px-4 py-2.5 flex items-center justify-between border-b border-slate-200 dark:border-slate-800 text-xs font-bold text-slate-800 dark:text-slate-200">
                <span>
                  {sem.level} — {sem.sessionId} ({sem.semesterId})
                </span>
                <span className="text-indigo-600 dark:text-indigo-400">
                  Term GPA: {sem.gpa.toFixed(2)} | Running CGPA: {sem.runningCGPA.toFixed(2)}
                </span>
              </div>

              <table className="w-full text-left text-xs text-slate-700 dark:text-slate-300">
                <thead className="bg-slate-50 dark:bg-slate-900 text-slate-500 font-semibold text-[11px] border-b border-slate-200 dark:border-slate-800">
                  <tr>
                    <th className="py-2 px-3">Course Code</th>
                    <th className="py-2 px-3">Course Title</th>
                    <th className="py-2 px-3 text-center">Category</th>
                    <th className="py-2 px-3 text-center">Units</th>
                    <th className="py-2 px-3 text-center">Score</th>
                    <th className="py-2 px-3 text-center">Grade</th>
                    <th className="py-2 px-3 text-center">Points</th>
                    <th className="py-2 px-3 text-center">QP</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {sem.courses.map((c, cIdx) => (
                    <tr key={cIdx} className="hover:bg-slate-50/50 dark:hover:bg-slate-900/50">
                      <td className="py-1.5 px-3 font-mono font-semibold text-slate-900 dark:text-white">
                        {c.courseCode}
                      </td>
                      <td className="py-1.5 px-3 text-slate-800 dark:text-slate-200">{c.courseTitle}</td>
                      <td className="py-1.5 px-3 text-center text-slate-500">{c.category}</td>
                      <td className="py-1.5 px-3 text-center font-medium">{c.creditUnit}</td>
                      <td className="py-1.5 px-3 text-center font-medium">{c.score}</td>
                      <td className="py-1.5 px-3 text-center font-bold">{c.letterGrade}</td>
                      <td className="py-1.5 px-3 text-center font-medium">{c.gradePoint.toFixed(1)}</td>
                      <td className="py-1.5 px-3 text-center font-bold text-amber-600 dark:text-amber-400">
                        {c.qualityPoints.toFixed(1)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
        </div>

        {/* TRANSCRIPT SUMMARY FOOTER */}
        <div className="mt-8 pt-6 border-t-2 border-slate-900 dark:border-slate-100 font-sans grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs">
            <h4 className="font-bold text-slate-900 dark:text-white uppercase mb-2">Graduation Summary</h4>
            <p className="text-slate-600 dark:text-slate-400 mb-1">
              Total Earned Credits: <strong className="text-slate-900 dark:text-white">{transcript.totalEarnedCredits} Units</strong>
            </p>
            <p className="text-slate-600 dark:text-slate-400 mb-1">
              Total Quality Points: <strong className="text-amber-600 dark:text-amber-400">{transcript.totalQualityPoints.toFixed(1)} pts</strong>
            </p>
            <p className="text-slate-600 dark:text-slate-400">
              Cumulative GPA: <strong className="text-indigo-600 dark:text-indigo-400 text-sm">{transcript.finalCGPA.toFixed(2)}</strong>
            </p>
          </div>

          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs">
            <h4 className="font-bold text-slate-900 dark:text-white uppercase mb-2">Degree Awarded</h4>
            <p className="text-slate-900 dark:text-white font-extrabold text-sm mb-1">
              {transcript.graduationClass}
            </p>
            <p className="text-emerald-600 dark:text-emerald-400 font-semibold flex items-center gap-1">
              <ShieldCheck className="w-4 h-4" /> Standing: {transcript.academicStanding}
            </p>
          </div>

          <div className="p-4 rounded-xl border border-dashed border-slate-300 dark:border-slate-700 flex flex-col justify-between text-xs text-center">
            <div className="pt-4">
              <p className="font-serif italic text-slate-500">Registrar Official Signature & Seal</p>
            </div>
            <div className="pt-4 border-t border-slate-200 dark:border-slate-800 text-[10px] text-slate-400">
              Verified electronically via StudyMate Academic Ledger • Ref: TRANS-{Date.now().toString(36).toUpperCase()}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
